//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Database.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentMSEntities1 : DbContext
    {
        public StudentMSEntities1()
            : base("name=StudentMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<TEACHER_COURSE_DETAIL> TEACHER_COURSE_DETAIL { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_COURSE> USER_COURSE { get; set; }
    
        public virtual ObjectResult<GetCourseUserDetail_Result> GetCourseUserDetail(Nullable<System.Guid> cOURSEID)
        {
            var cOURSEIDParameter = cOURSEID.HasValue ?
                new ObjectParameter("COURSEID", cOURSEID) :
                new ObjectParameter("COURSEID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseUserDetail_Result>("GetCourseUserDetail", cOURSEIDParameter);
        }
    
        public virtual ObjectResult<GetCourseContent_Result> GetCourseContent(Nullable<System.Guid> cOURSEID)
        {
            var cOURSEIDParameter = cOURSEID.HasValue ?
                new ObjectParameter("COURSEID", cOURSEID) :
                new ObjectParameter("COURSEID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseContent_Result>("GetCourseContent", cOURSEIDParameter);
        }
    
        public virtual ObjectResult<GetUserInfo_Result> GetUserInfo(string eMAIL, string pASSWORD)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInfo_Result>("GetUserInfo", eMAILParameter, pASSWORDParameter);
        }
    }
}
